@api = http://localhost:2000/Servidor

get {{api}}/MostrarUsuarios

###
POST {{api}}/RegistrarUsuarios
Content-Type: application/json

{
    "Nombre_Usuario": "José Jair",
    "Apellido_Usuario": "Lopez Herrera",
    "Correo_Electronico": "Prueba628@gmail.com",
    "Contraseña": "Contraseña2"
}

###

post {{api}}/EncontrarUsuario/2

###
DELETE  {{api}}/EliminarUsuario/1

###
GET {{api}}/ContarUsuarios

###
PUT {{api}}/irving@gmail.com
Content-Type: application/json

{
    "Nombre_Usuario": "José Jair",
    "Apellido_Usuario": "Lopez Herrera",
    "Correo_Electronico": "Prueba2@gmail.com",
    "Contraseña": "Contraseña2424"
}